package br.com.inventorymed.formtemplates;

public enum FormFieldType {
    SHORT_TEXT,
    LONG_TEXT,
    INTEGER,
    DECIMAL,
    DATE,
    TIME,
    SINGLE_SELECT,
    MULTI_SELECT,
    BOOLEAN,
    MEDICATION_LINE,
    CLINICAL_TABLE,
    DIET_PLAN,
    NURSING_CARE_PLAN,
    MONITORING_PLAN,
    VENTILATORY_SUPPORT_PLAN,
    REHABILITATION_PLAN,
    ISOLATION_PRECAUTIONS_PLAN
}
